### ISSUE TITLE
QQ: leave empty directories

### ISSUE THREAD

**Issue by mgaulton** [caronc/nzbget-tidyit#6]
So I'm loving the script but noticed that there's no way to leave empty directories, they get removed.
This makes SickRage upset, so I'm wondering if there's a way or mod to do this?

**Comment by caronc** [comment]
Sorry to take so long to get back to you.  I'm not as reliable as i used to be :frowning: 

Anyway, i just created a small branch to add a **KeepDirectories** directive (or **--keep-directories** or **-k** from the command line).  It will however still clean up meta directories that are empty though.

Please keep in mind that this request is kind of counter-intuitive (and defeats the original purpose of this script). However, when using this option now, you _will_ cause your media library to contain many _empty_ skeleton directories from past videos you may have removed.  That along would personally drive me nuts; that specifically was also what caused the creation of this script.

Since you're actually the second one to make this request ([the first request was made here](https://forum.nzbget.net/viewtopic.php?f=8&t=1975&start=10#p15721)), it only makes sense to offer it!

The real fix would be open a ticket or speak with the SickRage devs and see if they can make their app handle missing directories better though :wink:.

Regardless (i'm done ranting now - i promise): the features implemented now in this script! I'd be curious if the new switch accomplishes what you wanted! :smile: .

You can check out the latest code [here](https://github.com/caronc/nzbget-tidyit/archive/6-leave-empty-directories.zip).  The branch itself is [here](https://github.com/caronc/nzbget-tidyit/tree/6-leave-empty-directories).

**Comment by mgaulton** [comment]
They have code to recreate directories now, but it only triggers when you postprocess a new episode for that show as far as I can tell. for TV, my tree is only one layer, i don't break out seasons in folders or anything like that. 
Thank you!
