### ISSUE TITLE
safe-guarded files

### ISSUE THREAD

**Issue by ver2go** [caronc/nzbget-tidyit#8]
I some times have files such as the following and TidyIt blocks cleaning the directories because of them.
I can add them to the -t option, but the safe-guarded files vary and I have to hunt them down.  
I'm not sure why they are considered safe-guarded

Thanks

Samples below:

`
/de8c4fc4c9d9b3caacde7b72be637e.a4 (safe-guarded)
5b7359632b5c9890c664196eb.e7bf (safe-guarded)
MQ3TKZRTMU2TCNZQG42GEN3CGZDEYZQ (safe-guarded)
`

**Comment by caronc** [comment]
Basically those files are not video files, images, or subtitles.  If the script doesn't know what the extension is, then it doesn't touch them.  I can understand your frustration though because in this case it's obvious you'd prefer the script deleted them.

the thing is the script doesn't know of mp3's, documents, etc either so it will safely avoid them. The script does have an ```--always-trash (-t)``` command that may be useful to you. You could try running the tool as:
```bash
python TidyIt.py --always-trash ".a4,.e7bf" [your other options here]
```

Alternatively; those are some pretty cryptic/obfuscated file names; you could just find and purge them (if in Linux):
```bash
# delete de8c4fc4c9d9b3caacde7b72be637e.a4
find /path/to/your/library -type f -name '*.a4' -delete

# delete 5b7359632b5c9890c664196eb.e7bf
find /path/to/your/library -type f -name '*.e7bf' -delete

# delete MQ3TKZRTMU2TCNZQG42GEN3CGZDEYZQ
# without an extension; there isn't a whole lot you can do but exclusively
# search for this exact file:
find /path/to/your/library -type f -name 'MQ3TKZRTMU2TCNZQG42GEN3CGZDEYZQ' -delete
```

Hope this helps!

**Comment by ver2go** [comment]
Thanks for the explanation.  The part that threw me off was I was trying to get rid of 
.rar files in the same directory, 

`TidyIt.py -a 1  -t .rar`

When it encountered a directory with the "weird' files, it will not process any of the files.

For example a directory would have:

`foo.rar`
`movie.mkv`
`nfo.nfo`
`ABCDEDDD.B1E`
If I run `TidyIt.py -a 1  -t .rar _directory_`
It will not process any files in that directory, I thought that would at least delete `foo.rar` but it just abandoned processing anything in that directory.


Yeah I could add the files, but I never know the pattern. I just ended up using -D and grep'ed for safe to get a file list I had to go back and process.

**Comment by caronc** [comment]
I hear you.  The destruction I could unleash if i even just added an option to deleted what would have otherwise been a safeguarded file would probably make some people really angry :wink: . 

Especially if you accidentally scan a path that wasn't your library; the script would just wreck havoc on the system :slightly_smiling_face: .

Are you cool if i close this issue then, or would you like to see an option such as **--purge-safeguarded** or something to handle your situation?

Thoughts?

**Comment by ver2go** [comment]
I'll close this.  I understand the behavior now and completely agree about the risk.
