### ISSUE TITLE
Command line mode is broken

### ISSUE THREAD

**Issue by ookla-ariel-ride** [caronc/nzbget-tidyit#9]
the last update removed the nzbget directory and breaks the script.

this is the error I get:

Traceback (most recent call last):
  File "TidyIt.py", line 279, in <module>
    from nzbget import SKIP_DIRECTORIES
ImportError: No module named nzbget

**Comment by caronc** [comment]
Hi,

Run the following and it should fix you up:
```bash
# requirements.txt is located in the root of the TidyIt repository
pip install -r requirements.txt
```

This past week I've made all of my scripts (_except nzbget-subliminal_) backwards and forwards compatible with Python v3. In doing so i was able to clean a lot up.  For example _TidyIt.py_ no longer has or needs that sub-directory (_TidyIt_). This missing directory is where your import error is coming from.

Secondly it was kind of annoying to update all of the scripts i maintain (like this one) separately each time i had a new update to [pynzbget](https://github.com/caronc/pynzbget).  Having pynzbget installed in your global configuration just makes so much more sense (especially since it's on [PyPi](https://pypi.org/project/pynzbget/)). :slightly_smiling_face:

Hopefully this makes sense.  Run the command identified above and let me know if you're still having troubles after this.

**Comment by ookla-ariel-ride** [comment]
this worked, although I needed to run pip2 since I have both python 2  and python 3 installed.  I ran the requirements install for both versions of pip and now everything works again.  

thanks!

**Comment by caronc** [comment]
Hey,

I'm glad you got it going; sorry for the break without much knowledge; this package isn't used by a lot of people so i was kind of expecting a bug ticket on what i did eventually.  You were _that_ person :wink: 

In the future you shouldn't see any more hard breaks like this one was.  This change to drop all of the packages included in the **TidyIt** directory was for the best.

I'm going to close this ticket off.  Please feel free to re-open it or create another if you have any more issues!
